enum APIIntentTypeEnum {
  NO_INTENT = '',
  CREATE_ORDER = 'CREATE_ORDER',
  EDIT_ORDER = 'EDIT_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',
  DELETE_ORDER_FLOOR = 'DELETE_ORDER_FLOOR',
  DELETE_ORDER_ATTACHMENT = 'DELETE_ORDER_ATTACHMENT',
  ADD_ORDER_COMMENT = 'ADD_ORDER_COMMENT',
  ADD_ORDER_FLOOR = 'ADD_ORDER_FLOOR',
  ADD_ORDER_ATTACHMENT = 'ADD_ORDER_ATTACHMENT',
  ASSIGN_USER_TO_ORDER = 'ASSIGN_USER_TO_ORDER',
  CHANGE_ORDER_PRIORITY = 'CHANGE_ORDER_PRIORITY',
  INITIATE_ORDER_ACTION = 'INITIATE_ORDER_ACTION',
  INITIATE_ORDER_FLOOR_ACTION = 'INITIATE_ORDER_FLOOR_ACTION',
  LOG_ORDER_WORK_TIME = 'LOG_ORDER_WORK_TIME',
  LOG_ORDER_WORK_TIME_AND_FINISH = 'LOG_ORDER_WORK_TIME_AND_FINISH',
  LOG_ORDER_WORK_TIME_AND_UNASSIGN = 'LOG_ORDER_WORK_TIME_AND_UNASSIGN',
};

export type APIIntentType = keyof typeof APIIntentTypeEnum;
